export const ORGANIZATION_TYPES = ['Hospital', 'Hotel', 'Company', 'University'];

export const CATEGORY_COMPLAINTS_MAP = {
  Hospital: [
    'Dhaqaatiirta & Baaritaanka (Doctors & Consultation)',
    'Kalkaaliyeyaasha & Daryeelka (Nursing & Care)',
    'Daawada & Farmashiyaha (Pharmacy & Drugs)',
    'Nadaafadda & Qolalka (Hygiene & Rooms)',
    'Xaaladaha Degdegga ah (Emergency Response)',
    'Waqtiga & Safafka Sugitaanka (Wait Times)',
    'Shaybaarka & Baaritaannada (Lab & Scans)',
    'Qiimaha & Lacag-bixinta (Billing & Prices)',
    'Anshaxa Shaqaalaha (Staff Ethics & Respect)',
    'Qalabka & Kaabayaasha (Medical Facilities)',
  ],
  Hotel: [
    'Nadaafadda Qolka & Sariiraha (Room Cleanliness)',
    'Cuntada & Quraaca (Food Quality & Breakfast)',
    'Adeegga Qolalka (Room Service)',
    'Dabeecadda Shaqaalaha (Staff Hospitality)',
    'Wi-Fi-ga & Internetka (Wi-Fi & Speed)',
    'Qaboojiyaha & Biyaha (AC & Hot Water)',
    'Nabadgelyada & Qasnada (Security)',
    'Qiimaha & Xisaab-xirka (Billing & Checkout)',
    'Buuqa & Deganaanshaha (Noise & Comfort)',
    'Adeegyada Dheeraadka ah (Parking & Facilities)',
  ],
  Company: [
    'Tayada Badeecada / Adeegga (Product Quality)',
    'Gaarsiinta & Waqtiga (Delivery & Timeliness)',
    'Adeegga Macmiilka (Customer Support)',
    'Qiimaha & Qaansheegadka (Pricing & Invoicing)',
    'Heshiisyada & Shuruudaha (Contracts & Terms)',
    'Taageerada Farsamada (Technical Support)',
    'Soo Celinta & Magdhawga (Refunds & Returns)',
    'Dhaqanka Shaqaalaha (Employee Conduct)',
    'Xiriirka & Xog-siinta (Communication)',
    'Nidaamka Lacag-bixinta (Payment Gateway)',
  ],
  University: [
    'Tayada Macallimiinta & Barashada (Lecturers & Teaching)',
    'Jadwalka & Fasallada (Class Schedules)',
    'Imtixaanaadka & Natiijooyinka (Exams & Grading)',
    'Maktabadda & Agabka (Library & Books)',
    'Shaybaarrada & ICT (Computer Labs & Tech)',
    'Maamulka & Diiwaangelinta (Registrar & Admin)',
    'Fiidka & Lacagaha (Tuition & Finance)',
    'Nadaafadda Dhismaha (Campus Cleanliness)',
    'Anshaxa & Cadaaladda (Ethics & Fairness)',
    'Adeegyada Ardayda (Student Affairs)',
  ],
};
