export const ORGANIZATION_STATUS = {
  ACTIVE: 'ACTIVE',
  EXPIRING_SOON: 'EXPIRING_SOON',
  EXPIRED: 'EXPIRED',
  GRACE_PERIOD: 'GRACE_PERIOD',
  INACTIVE: 'INACTIVE',
};

export const QR_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  REVOKED: 'REVOKED',
};

export const SUBSCRIPTION_STATUS = {
  ACTIVE: 'ACTIVE',
  EXPIRING_SOON: 'EXPIRING_SOON',
  EXPIRED: 'EXPIRED',
  GRACE_PERIOD: 'GRACE_PERIOD',
  INACTIVE: 'INACTIVE',
};

export const RENEWAL_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
};

export const SUBMISSION_TYPE = {
  COMPLAINT: 'COMPLAINT', // CABASHO
  FEEDBACK: 'FEEDBACK',   // TALO
};

export const COMPLAINT_STATUS = {
  NEW: 'NEW',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
  REJECTED: 'REJECTED',
};

export const COMPLAINT_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
};

export const NOTIFICATION_STATUS = {
  SENT: 'SENT',
  FAILED: 'FAILED',
  PENDING: 'PENDING',
  RETRIED: 'RETRIED',
};

export const NOTIFICATION_CHANNEL = {
  SMS: 'SMS',
  WHATSAPP: 'WHATSAPP',
  EMAIL: 'EMAIL',
};

export const NOTIFICATION_TYPE = {
  COMPLAINT: 'COMPLAINT',
  SUGGESTION: 'SUGGESTION',
  ACCOUNT_CREATION: 'ACCOUNT_CREATION',
  CUSTOMER_THANK_YOU: 'CUSTOMER_THANK_YOU',
  GENERAL: 'GENERAL',
};

export const PAYMENT_METHOD = {
  CASH: 'Cash',
  BANK_TRANSFER: 'Bank Transfer',
  MOBILE_MONEY: 'Mobile Money',
  OTHER: 'Other',
};
