export const ORGANIZATION_TYPES = [
  'HOTEL',
  'UNIVERSITY',
  'COMPANY',
  'HOSPITAL',
];

export const CATEGORY_COMPLAINTS_MAP = {
  HOTEL: [
    'Room Service',
    'Staff Service',
    'Cleanliness',
    'Food & Dining',
    'Reception',
    'Room Facilities',
    'Security',
    'Billing & Payment',
    'Maintenance',
    'Customer Service',
  ],
  UNIVERSITY: [
    'Teaching Quality',
    'Lecturer',
    'Registration',
    'Examination',
    'Student Services',
    'Library',
    'Facilities',
    'Administration',
    'Fees & Payment',
    'Campus Services',
  ],
  COMPANY: [
    'Customer Service',
    'Staff',
    'Product/Service',
    'Billing & Payment',
    'Delivery',
    'Facilities',
    'Support',
    'Security',
    'Operations',
    'Management',
  ],
  HOSPITAL: [
    'Doctor Service',
    'Nursing Service',
    'Reception',
    'Waiting Time',
    'Cleanliness',
    'Pharmacy',
    'Laboratory',
    'Billing & Payment',
    'Facilities',
    'Patient Service',
  ],
  // Capitalized aliases
  Hotel: [
    'Room Service',
    'Staff Service',
    'Cleanliness',
    'Food & Dining',
    'Reception',
    'Room Facilities',
    'Security',
    'Billing & Payment',
    'Maintenance',
    'Customer Service',
  ],
  University: [
    'Teaching Quality',
    'Lecturer',
    'Registration',
    'Examination',
    'Student Services',
    'Library',
    'Facilities',
    'Administration',
    'Fees & Payment',
    'Campus Services',
  ],
  Company: [
    'Customer Service',
    'Staff',
    'Product/Service',
    'Billing & Payment',
    'Delivery',
    'Facilities',
    'Support',
    'Security',
    'Operations',
    'Management',
  ],
  Hospital: [
    'Doctor Service',
    'Nursing Service',
    'Reception',
    'Waiting Time',
    'Cleanliness',
    'Pharmacy',
    'Laboratory',
    'Billing & Payment',
    'Facilities',
    'Patient Service',
  ],
};

export const getCategoriesForType = (type) => {
  if (!type) return [];
  const normalized = type.toUpperCase();
  return CATEGORY_COMPLAINTS_MAP[normalized] || CATEGORY_COMPLAINTS_MAP[type] || [];
};
